### ISSUE TITLE
Upgrade to Spring Boot 2.1.6 for both master tool and scdf-app-repo

### ISSUE THREAD

**Issue by jackycct** [spring-cloud-stream-app-starters/scdf-app-tool#8]
Upgrade from Spring Boot 2.0.3.RELEASE to 2.1.6.RELEASE

**Comment by sabbyanandan** [comment]
Addressed in https://github.com/spring-cloud-stream-app-starters/scdf-app-tool/commit/a13039363651f8c57c11759040a070029b169b8c.
